/* soapMLWebServiceSoapBindingProxy.h
   Generated by gSOAP 2.7.10 from soapMLWebService.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapMLWebServiceSoapBindingProxy_H
#define soapMLWebServiceSoapBindingProxy_H
#include "soapH.h"
class MLWebServiceSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'MLWebServiceSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	MLWebServiceSoapBinding()
	{ soap = soap_new(); endpoint = "http://aliendb1:6004/axis/services/MLWebService"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://xml.apache.org/xml-soap", NULL, NULL},
	{"ns1", "urn:lia.ws", NULL, NULL},
	{"ns3", "http://ws.lia", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~MLWebServiceSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'networkMeasurementSet' of service 'MLWebServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int ns3__networkMeasurementSet(ns2__Map *_in0, struct ns3__networkMeasurementSetResponse &_param_6) { return soap ? soap_call_ns3__networkMeasurementSet(soap, endpoint, NULL, _in0, _param_6) : SOAP_EOM; };
};
#endif
