/* soapH.h
   Generated by gSOAP 2.7.10 from soapMLWebService.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_ArrayOf_USCOREtns1_USCOREWSConf
#define SOAP_TYPE_ArrayOf_USCOREtns1_USCOREWSConf (25)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, const char*, int, const ArrayOf_USCOREtns1_USCOREWSConf *, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSConf * SOAP_FMAC4 soap_get_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, ArrayOf_USCOREtns1_USCOREWSConf *, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSConf * SOAP_FMAC4 soap_in_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREWSConf *, const char*);
SOAP_FMAC5 ArrayOf_USCOREtns1_USCOREWSConf * SOAP_FMAC6 soap_new_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, ArrayOf_USCOREtns1_USCOREWSConf*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSConf * SOAP_FMAC4 soap_instantiate_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOf_USCOREtns1_USCOREWSConf(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOf_USCOREtns1_USCOREWSCluster
#define SOAP_TYPE_ArrayOf_USCOREtns1_USCOREWSCluster (24)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, const char*, int, const ArrayOf_USCOREtns1_USCOREWSCluster *, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSCluster * SOAP_FMAC4 soap_get_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, ArrayOf_USCOREtns1_USCOREWSCluster *, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSCluster * SOAP_FMAC4 soap_in_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREWSCluster *, const char*);
SOAP_FMAC5 ArrayOf_USCOREtns1_USCOREWSCluster * SOAP_FMAC6 soap_new_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, ArrayOf_USCOREtns1_USCOREWSCluster*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSCluster * SOAP_FMAC4 soap_instantiate_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOf_USCOREtns1_USCOREWSNode
#define SOAP_TYPE_ArrayOf_USCOREtns1_USCOREWSNode (23)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, const char*, int, const ArrayOf_USCOREtns1_USCOREWSNode *, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSNode * SOAP_FMAC4 soap_get_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, ArrayOf_USCOREtns1_USCOREWSNode *, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSNode * SOAP_FMAC4 soap_in_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREWSNode *, const char*);
SOAP_FMAC5 ArrayOf_USCOREtns1_USCOREWSNode * SOAP_FMAC6 soap_new_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, ArrayOf_USCOREtns1_USCOREWSNode*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSNode * SOAP_FMAC4 soap_instantiate_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOf_USCOREtns1_USCOREWSNode(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring (22)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, int, const ArrayOf_USCORExsd_USCOREstring *, const char*);
SOAP_FMAC3 ArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_get_ArrayOf_USCORExsd_USCOREstring(struct soap*, ArrayOf_USCORExsd_USCOREstring *, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_in_ArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, ArrayOf_USCORExsd_USCOREstring *, const char*);
SOAP_FMAC5 ArrayOf_USCORExsd_USCOREstring * SOAP_FMAC6 soap_new_ArrayOf_USCORExsd_USCOREstring(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOf_USCORExsd_USCOREstring(struct soap*, ArrayOf_USCORExsd_USCOREstring*);
SOAP_FMAC3 ArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_instantiate_ArrayOf_USCORExsd_USCOREstring(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOf_USCORExsd_USCOREstring(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOf_USCOREtns1_USCOREResult
#define SOAP_TYPE_ArrayOf_USCOREtns1_USCOREResult (21)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCOREtns1_USCOREResult(struct soap*, const char*, int, const ArrayOf_USCOREtns1_USCOREResult *, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREResult * SOAP_FMAC4 soap_get_ArrayOf_USCOREtns1_USCOREResult(struct soap*, ArrayOf_USCOREtns1_USCOREResult *, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREResult * SOAP_FMAC4 soap_in_ArrayOf_USCOREtns1_USCOREResult(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREResult *, const char*);
SOAP_FMAC5 ArrayOf_USCOREtns1_USCOREResult * SOAP_FMAC6 soap_new_ArrayOf_USCOREtns1_USCOREResult(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOf_USCOREtns1_USCOREResult(struct soap*, ArrayOf_USCOREtns1_USCOREResult*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREResult * SOAP_FMAC4 soap_instantiate_ArrayOf_USCOREtns1_USCOREResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOf_USCOREtns1_USCOREResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__WSConf
#define SOAP_TYPE_ns3__WSConf (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__WSConf(struct soap*, const char*, int, const ns3__WSConf *, const char*);
SOAP_FMAC3 ns3__WSConf * SOAP_FMAC4 soap_get_ns3__WSConf(struct soap*, ns3__WSConf *, const char*, const char*);
SOAP_FMAC3 ns3__WSConf * SOAP_FMAC4 soap_in_ns3__WSConf(struct soap*, const char*, ns3__WSConf *, const char*);
SOAP_FMAC5 ns3__WSConf * SOAP_FMAC6 soap_new_ns3__WSConf(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__WSConf(struct soap*, ns3__WSConf*);
SOAP_FMAC3 ns3__WSConf * SOAP_FMAC4 soap_instantiate_ns3__WSConf(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__WSConf(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__WSFarm
#define SOAP_TYPE_ns3__WSFarm (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__WSFarm(struct soap*, const char*, int, const ns3__WSFarm *, const char*);
SOAP_FMAC3 ns3__WSFarm * SOAP_FMAC4 soap_get_ns3__WSFarm(struct soap*, ns3__WSFarm *, const char*, const char*);
SOAP_FMAC3 ns3__WSFarm * SOAP_FMAC4 soap_in_ns3__WSFarm(struct soap*, const char*, ns3__WSFarm *, const char*);
SOAP_FMAC5 ns3__WSFarm * SOAP_FMAC6 soap_new_ns3__WSFarm(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__WSFarm(struct soap*, ns3__WSFarm*);
SOAP_FMAC3 ns3__WSFarm * SOAP_FMAC4 soap_instantiate_ns3__WSFarm(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__WSFarm(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__WSCluster
#define SOAP_TYPE_ns3__WSCluster (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__WSCluster(struct soap*, const char*, int, const ns3__WSCluster *, const char*);
SOAP_FMAC3 ns3__WSCluster * SOAP_FMAC4 soap_get_ns3__WSCluster(struct soap*, ns3__WSCluster *, const char*, const char*);
SOAP_FMAC3 ns3__WSCluster * SOAP_FMAC4 soap_in_ns3__WSCluster(struct soap*, const char*, ns3__WSCluster *, const char*);
SOAP_FMAC5 ns3__WSCluster * SOAP_FMAC6 soap_new_ns3__WSCluster(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__WSCluster(struct soap*, ns3__WSCluster*);
SOAP_FMAC3 ns3__WSCluster * SOAP_FMAC4 soap_instantiate_ns3__WSCluster(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__WSCluster(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__WSNode
#define SOAP_TYPE_ns3__WSNode (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__WSNode(struct soap*, const char*, int, const ns3__WSNode *, const char*);
SOAP_FMAC3 ns3__WSNode * SOAP_FMAC4 soap_get_ns3__WSNode(struct soap*, ns3__WSNode *, const char*, const char*);
SOAP_FMAC3 ns3__WSNode * SOAP_FMAC4 soap_in_ns3__WSNode(struct soap*, const char*, ns3__WSNode *, const char*);
SOAP_FMAC5 ns3__WSNode * SOAP_FMAC6 soap_new_ns3__WSNode(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__WSNode(struct soap*, ns3__WSNode*);
SOAP_FMAC3 ns3__WSNode * SOAP_FMAC4 soap_instantiate_ns3__WSNode(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__WSNode(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__Result
#define SOAP_TYPE_ns3__Result (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__Result(struct soap*, const char*, int, const ns3__Result *, const char*);
SOAP_FMAC3 ns3__Result * SOAP_FMAC4 soap_get_ns3__Result(struct soap*, ns3__Result *, const char*, const char*);
SOAP_FMAC3 ns3__Result * SOAP_FMAC4 soap_in_ns3__Result(struct soap*, const char*, ns3__Result *, const char*);
SOAP_FMAC5 ns3__Result * SOAP_FMAC6 soap_new_ns3__Result(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__Result(struct soap*, ns3__Result*);
SOAP_FMAC3 ns3__Result * SOAP_FMAC4 soap_instantiate_ns3__Result(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__Result(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__Map
#define SOAP_TYPE_ns2__Map (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Map(struct soap*, const char*, int, const ns2__Map *, const char*);
SOAP_FMAC3 ns2__Map * SOAP_FMAC4 soap_get_ns2__Map(struct soap*, ns2__Map *, const char*, const char*);
SOAP_FMAC3 ns2__Map * SOAP_FMAC4 soap_in_ns2__Map(struct soap*, const char*, ns2__Map *, const char*);
SOAP_FMAC5 ns2__Map * SOAP_FMAC6 soap_new_ns2__Map(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__Map(struct soap*, ns2__Map*);
SOAP_FMAC3 ns2__Map * SOAP_FMAC4 soap_instantiate_ns2__Map(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__Map(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__mapItem
#define SOAP_TYPE_ns2__mapItem (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__mapItem(struct soap*, const char*, int, const ns2__mapItem *, const char*);
SOAP_FMAC3 ns2__mapItem * SOAP_FMAC4 soap_get_ns2__mapItem(struct soap*, ns2__mapItem *, const char*, const char*);
SOAP_FMAC3 ns2__mapItem * SOAP_FMAC4 soap_in_ns2__mapItem(struct soap*, const char*, ns2__mapItem *, const char*);
SOAP_FMAC5 ns2__mapItem * SOAP_FMAC6 soap_new_ns2__mapItem(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__mapItem(struct soap*, ns2__mapItem*);
SOAP_FMAC3 ns2__mapItem * SOAP_FMAC4 soap_instantiate_ns2__mapItem(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__mapItem(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, const xsd__string *, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_get_xsd__string(struct soap*, xsd__string *, const char*, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, xsd__string *, const char*);
SOAP_FMAC5 xsd__string * SOAP_FMAC6 soap_new_xsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string(struct soap*, xsd__string*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_instantiate_xsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const xsd__long *, const char*);
SOAP_FMAC3 xsd__long * SOAP_FMAC4 soap_get_xsd__long(struct soap*, xsd__long *, const char*, const char*);
SOAP_FMAC3 xsd__long * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, xsd__long *, const char*);
SOAP_FMAC5 xsd__long * SOAP_FMAC6 soap_new_xsd__long(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__long(struct soap*, xsd__long*);
SOAP_FMAC3 xsd__long * SOAP_FMAC4 soap_instantiate_xsd__long(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__long(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);
SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, xsd__anyType*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns3__networkMeasurementSet
#define SOAP_TYPE_ns3__networkMeasurementSet (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__networkMeasurementSet(struct soap*, struct ns3__networkMeasurementSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__networkMeasurementSet(struct soap*, const struct ns3__networkMeasurementSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__networkMeasurementSet(struct soap*, const struct ns3__networkMeasurementSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__networkMeasurementSet(struct soap*, const char*, int, const struct ns3__networkMeasurementSet *, const char*);
SOAP_FMAC3 struct ns3__networkMeasurementSet * SOAP_FMAC4 soap_get_ns3__networkMeasurementSet(struct soap*, struct ns3__networkMeasurementSet *, const char*, const char*);
SOAP_FMAC3 struct ns3__networkMeasurementSet * SOAP_FMAC4 soap_in_ns3__networkMeasurementSet(struct soap*, const char*, struct ns3__networkMeasurementSet *, const char*);
SOAP_FMAC5 struct ns3__networkMeasurementSet * SOAP_FMAC6 soap_new_ns3__networkMeasurementSet(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__networkMeasurementSet(struct soap*, struct ns3__networkMeasurementSet*);
SOAP_FMAC3 struct ns3__networkMeasurementSet * SOAP_FMAC4 soap_instantiate_ns3__networkMeasurementSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__networkMeasurementSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__networkMeasurementSetResponse
#define SOAP_TYPE_ns3__networkMeasurementSetResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__networkMeasurementSetResponse(struct soap*, struct ns3__networkMeasurementSetResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__networkMeasurementSetResponse(struct soap*, const struct ns3__networkMeasurementSetResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__networkMeasurementSetResponse(struct soap*, const struct ns3__networkMeasurementSetResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__networkMeasurementSetResponse(struct soap*, const char*, int, const struct ns3__networkMeasurementSetResponse *, const char*);
SOAP_FMAC3 struct ns3__networkMeasurementSetResponse * SOAP_FMAC4 soap_get_ns3__networkMeasurementSetResponse(struct soap*, struct ns3__networkMeasurementSetResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__networkMeasurementSetResponse * SOAP_FMAC4 soap_in_ns3__networkMeasurementSetResponse(struct soap*, const char*, struct ns3__networkMeasurementSetResponse *, const char*);
SOAP_FMAC5 struct ns3__networkMeasurementSetResponse * SOAP_FMAC6 soap_new_ns3__networkMeasurementSetResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__networkMeasurementSetResponse(struct soap*, struct ns3__networkMeasurementSetResponse*);
SOAP_FMAC3 struct ns3__networkMeasurementSetResponse * SOAP_FMAC4 soap_instantiate_ns3__networkMeasurementSetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__networkMeasurementSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getFilteredLastValues
#define SOAP_TYPE_ns1__getFilteredLastValues (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getFilteredLastValues(struct soap*, struct ns1__getFilteredLastValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getFilteredLastValues(struct soap*, const struct ns1__getFilteredLastValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getFilteredLastValues(struct soap*, const struct ns1__getFilteredLastValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getFilteredLastValues(struct soap*, const char*, int, const struct ns1__getFilteredLastValues *, const char*);
SOAP_FMAC3 struct ns1__getFilteredLastValues * SOAP_FMAC4 soap_get_ns1__getFilteredLastValues(struct soap*, struct ns1__getFilteredLastValues *, const char*, const char*);
SOAP_FMAC3 struct ns1__getFilteredLastValues * SOAP_FMAC4 soap_in_ns1__getFilteredLastValues(struct soap*, const char*, struct ns1__getFilteredLastValues *, const char*);
SOAP_FMAC5 struct ns1__getFilteredLastValues * SOAP_FMAC6 soap_new_ns1__getFilteredLastValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getFilteredLastValues(struct soap*, struct ns1__getFilteredLastValues*);
SOAP_FMAC3 struct ns1__getFilteredLastValues * SOAP_FMAC4 soap_instantiate_ns1__getFilteredLastValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getFilteredLastValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getFilteredLastValuesResponse
#define SOAP_TYPE_ns1__getFilteredLastValuesResponse (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getFilteredLastValuesResponse(struct soap*, struct ns1__getFilteredLastValuesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getFilteredLastValuesResponse(struct soap*, const struct ns1__getFilteredLastValuesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getFilteredLastValuesResponse(struct soap*, const struct ns1__getFilteredLastValuesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getFilteredLastValuesResponse(struct soap*, const char*, int, const struct ns1__getFilteredLastValuesResponse *, const char*);
SOAP_FMAC3 struct ns1__getFilteredLastValuesResponse * SOAP_FMAC4 soap_get_ns1__getFilteredLastValuesResponse(struct soap*, struct ns1__getFilteredLastValuesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getFilteredLastValuesResponse * SOAP_FMAC4 soap_in_ns1__getFilteredLastValuesResponse(struct soap*, const char*, struct ns1__getFilteredLastValuesResponse *, const char*);
SOAP_FMAC5 struct ns1__getFilteredLastValuesResponse * SOAP_FMAC6 soap_new_ns1__getFilteredLastValuesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getFilteredLastValuesResponse(struct soap*, struct ns1__getFilteredLastValuesResponse*);
SOAP_FMAC3 struct ns1__getFilteredLastValuesResponse * SOAP_FMAC4 soap_instantiate_ns1__getFilteredLastValuesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getFilteredLastValuesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getLastValues
#define SOAP_TYPE_ns1__getLastValues (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getLastValues(struct soap*, struct ns1__getLastValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getLastValues(struct soap*, const struct ns1__getLastValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getLastValues(struct soap*, const struct ns1__getLastValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getLastValues(struct soap*, const char*, int, const struct ns1__getLastValues *, const char*);
SOAP_FMAC3 struct ns1__getLastValues * SOAP_FMAC4 soap_get_ns1__getLastValues(struct soap*, struct ns1__getLastValues *, const char*, const char*);
SOAP_FMAC3 struct ns1__getLastValues * SOAP_FMAC4 soap_in_ns1__getLastValues(struct soap*, const char*, struct ns1__getLastValues *, const char*);
SOAP_FMAC5 struct ns1__getLastValues * SOAP_FMAC6 soap_new_ns1__getLastValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getLastValues(struct soap*, struct ns1__getLastValues*);
SOAP_FMAC3 struct ns1__getLastValues * SOAP_FMAC4 soap_instantiate_ns1__getLastValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getLastValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getLastValuesResponse
#define SOAP_TYPE_ns1__getLastValuesResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getLastValuesResponse(struct soap*, struct ns1__getLastValuesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getLastValuesResponse(struct soap*, const struct ns1__getLastValuesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getLastValuesResponse(struct soap*, const struct ns1__getLastValuesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getLastValuesResponse(struct soap*, const char*, int, const struct ns1__getLastValuesResponse *, const char*);
SOAP_FMAC3 struct ns1__getLastValuesResponse * SOAP_FMAC4 soap_get_ns1__getLastValuesResponse(struct soap*, struct ns1__getLastValuesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getLastValuesResponse * SOAP_FMAC4 soap_in_ns1__getLastValuesResponse(struct soap*, const char*, struct ns1__getLastValuesResponse *, const char*);
SOAP_FMAC5 struct ns1__getLastValuesResponse * SOAP_FMAC6 soap_new_ns1__getLastValuesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getLastValuesResponse(struct soap*, struct ns1__getLastValuesResponse*);
SOAP_FMAC3 struct ns1__getLastValuesResponse * SOAP_FMAC4 soap_instantiate_ns1__getLastValuesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getLastValuesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getLatestConfiguration
#define SOAP_TYPE_ns1__getLatestConfiguration (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getLatestConfiguration(struct soap*, struct ns1__getLatestConfiguration *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getLatestConfiguration(struct soap*, const struct ns1__getLatestConfiguration *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getLatestConfiguration(struct soap*, const struct ns1__getLatestConfiguration *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getLatestConfiguration(struct soap*, const char*, int, const struct ns1__getLatestConfiguration *, const char*);
SOAP_FMAC3 struct ns1__getLatestConfiguration * SOAP_FMAC4 soap_get_ns1__getLatestConfiguration(struct soap*, struct ns1__getLatestConfiguration *, const char*, const char*);
SOAP_FMAC3 struct ns1__getLatestConfiguration * SOAP_FMAC4 soap_in_ns1__getLatestConfiguration(struct soap*, const char*, struct ns1__getLatestConfiguration *, const char*);
SOAP_FMAC5 struct ns1__getLatestConfiguration * SOAP_FMAC6 soap_new_ns1__getLatestConfiguration(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getLatestConfiguration(struct soap*, struct ns1__getLatestConfiguration*);
SOAP_FMAC3 struct ns1__getLatestConfiguration * SOAP_FMAC4 soap_instantiate_ns1__getLatestConfiguration(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getLatestConfiguration(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getLatestConfigurationResponse
#define SOAP_TYPE_ns1__getLatestConfigurationResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getLatestConfigurationResponse(struct soap*, struct ns1__getLatestConfigurationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getLatestConfigurationResponse(struct soap*, const struct ns1__getLatestConfigurationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getLatestConfigurationResponse(struct soap*, const struct ns1__getLatestConfigurationResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getLatestConfigurationResponse(struct soap*, const char*, int, const struct ns1__getLatestConfigurationResponse *, const char*);
SOAP_FMAC3 struct ns1__getLatestConfigurationResponse * SOAP_FMAC4 soap_get_ns1__getLatestConfigurationResponse(struct soap*, struct ns1__getLatestConfigurationResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getLatestConfigurationResponse * SOAP_FMAC4 soap_in_ns1__getLatestConfigurationResponse(struct soap*, const char*, struct ns1__getLatestConfigurationResponse *, const char*);
SOAP_FMAC5 struct ns1__getLatestConfigurationResponse * SOAP_FMAC6 soap_new_ns1__getLatestConfigurationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getLatestConfigurationResponse(struct soap*, struct ns1__getLatestConfigurationResponse*);
SOAP_FMAC3 struct ns1__getLatestConfigurationResponse * SOAP_FMAC4 soap_instantiate_ns1__getLatestConfigurationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getLatestConfigurationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getConfiguration
#define SOAP_TYPE_ns1__getConfiguration (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getConfiguration(struct soap*, struct ns1__getConfiguration *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getConfiguration(struct soap*, const struct ns1__getConfiguration *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getConfiguration(struct soap*, const struct ns1__getConfiguration *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getConfiguration(struct soap*, const char*, int, const struct ns1__getConfiguration *, const char*);
SOAP_FMAC3 struct ns1__getConfiguration * SOAP_FMAC4 soap_get_ns1__getConfiguration(struct soap*, struct ns1__getConfiguration *, const char*, const char*);
SOAP_FMAC3 struct ns1__getConfiguration * SOAP_FMAC4 soap_in_ns1__getConfiguration(struct soap*, const char*, struct ns1__getConfiguration *, const char*);
SOAP_FMAC5 struct ns1__getConfiguration * SOAP_FMAC6 soap_new_ns1__getConfiguration(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getConfiguration(struct soap*, struct ns1__getConfiguration*);
SOAP_FMAC3 struct ns1__getConfiguration * SOAP_FMAC4 soap_instantiate_ns1__getConfiguration(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getConfiguration(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getConfigurationResponse
#define SOAP_TYPE_ns1__getConfigurationResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getConfigurationResponse(struct soap*, struct ns1__getConfigurationResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getConfigurationResponse(struct soap*, const struct ns1__getConfigurationResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getConfigurationResponse(struct soap*, const struct ns1__getConfigurationResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getConfigurationResponse(struct soap*, const char*, int, const struct ns1__getConfigurationResponse *, const char*);
SOAP_FMAC3 struct ns1__getConfigurationResponse * SOAP_FMAC4 soap_get_ns1__getConfigurationResponse(struct soap*, struct ns1__getConfigurationResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getConfigurationResponse * SOAP_FMAC4 soap_in_ns1__getConfigurationResponse(struct soap*, const char*, struct ns1__getConfigurationResponse *, const char*);
SOAP_FMAC5 struct ns1__getConfigurationResponse * SOAP_FMAC6 soap_new_ns1__getConfigurationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getConfigurationResponse(struct soap*, struct ns1__getConfigurationResponse*);
SOAP_FMAC3 struct ns1__getConfigurationResponse * SOAP_FMAC4 soap_instantiate_ns1__getConfigurationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getConfigurationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getValues
#define SOAP_TYPE_ns1__getValues (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getValues(struct soap*, struct ns1__getValues *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getValues(struct soap*, const struct ns1__getValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getValues(struct soap*, const struct ns1__getValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getValues(struct soap*, const char*, int, const struct ns1__getValues *, const char*);
SOAP_FMAC3 struct ns1__getValues * SOAP_FMAC4 soap_get_ns1__getValues(struct soap*, struct ns1__getValues *, const char*, const char*);
SOAP_FMAC3 struct ns1__getValues * SOAP_FMAC4 soap_in_ns1__getValues(struct soap*, const char*, struct ns1__getValues *, const char*);
SOAP_FMAC5 struct ns1__getValues * SOAP_FMAC6 soap_new_ns1__getValues(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getValues(struct soap*, struct ns1__getValues*);
SOAP_FMAC3 struct ns1__getValues * SOAP_FMAC4 soap_instantiate_ns1__getValues(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getValues(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getValuesResponse
#define SOAP_TYPE_ns1__getValuesResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getValuesResponse(struct soap*, struct ns1__getValuesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getValuesResponse(struct soap*, const struct ns1__getValuesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getValuesResponse(struct soap*, const struct ns1__getValuesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getValuesResponse(struct soap*, const char*, int, const struct ns1__getValuesResponse *, const char*);
SOAP_FMAC3 struct ns1__getValuesResponse * SOAP_FMAC4 soap_get_ns1__getValuesResponse(struct soap*, struct ns1__getValuesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getValuesResponse * SOAP_FMAC4 soap_in_ns1__getValuesResponse(struct soap*, const char*, struct ns1__getValuesResponse *, const char*);
SOAP_FMAC5 struct ns1__getValuesResponse * SOAP_FMAC6 soap_new_ns1__getValuesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getValuesResponse(struct soap*, struct ns1__getValuesResponse*);
SOAP_FMAC3 struct ns1__getValuesResponse * SOAP_FMAC4 soap_instantiate_ns1__getValuesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getValuesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREWSConf
#define SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREWSConf (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCOREtns1_USCOREWSConf(struct soap*, ArrayOf_USCOREtns1_USCOREWSConf *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCOREtns1_USCOREWSConf(struct soap*, ArrayOf_USCOREtns1_USCOREWSConf *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCOREtns1_USCOREWSConf(struct soap*, const char *, int, ArrayOf_USCOREtns1_USCOREWSConf *const*, const char *);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSConf ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCOREtns1_USCOREWSConf(struct soap*, ArrayOf_USCOREtns1_USCOREWSConf **, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSConf ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCOREtns1_USCOREWSConf(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREWSConf **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREResult
#define SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREResult (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCOREtns1_USCOREResult(struct soap*, ArrayOf_USCOREtns1_USCOREResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCOREtns1_USCOREResult(struct soap*, ArrayOf_USCOREtns1_USCOREResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCOREtns1_USCOREResult(struct soap*, const char *, int, ArrayOf_USCOREtns1_USCOREResult *const*, const char *);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREResult ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCOREtns1_USCOREResult(struct soap*, ArrayOf_USCOREtns1_USCOREResult **, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREResult ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCOREtns1_USCOREResult(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREResult **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons3__WSConf
#define SOAP_TYPE_PointerToPointerTons3__WSConf (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons3__WSConf(struct soap*, ns3__WSConf **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons3__WSConf(struct soap*, ns3__WSConf **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons3__WSConf(struct soap*, const char *, int, ns3__WSConf **const*, const char *);
SOAP_FMAC3 ns3__WSConf *** SOAP_FMAC4 soap_get_PointerToPointerTons3__WSConf(struct soap*, ns3__WSConf ***, const char*, const char*);
SOAP_FMAC3 ns3__WSConf *** SOAP_FMAC4 soap_in_PointerToPointerTons3__WSConf(struct soap*, const char*, ns3__WSConf ***, const char*);

#ifndef SOAP_TYPE_PointerTons3__WSConf
#define SOAP_TYPE_PointerTons3__WSConf (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__WSConf(struct soap*, ns3__WSConf *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__WSConf(struct soap*, ns3__WSConf *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__WSConf(struct soap*, const char *, int, ns3__WSConf *const*, const char *);
SOAP_FMAC3 ns3__WSConf ** SOAP_FMAC4 soap_get_PointerTons3__WSConf(struct soap*, ns3__WSConf **, const char*, const char*);
SOAP_FMAC3 ns3__WSConf ** SOAP_FMAC4 soap_in_PointerTons3__WSConf(struct soap*, const char*, ns3__WSConf **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons3__WSCluster
#define SOAP_TYPE_PointerToPointerTons3__WSCluster (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons3__WSCluster(struct soap*, ns3__WSCluster **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons3__WSCluster(struct soap*, ns3__WSCluster **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons3__WSCluster(struct soap*, const char *, int, ns3__WSCluster **const*, const char *);
SOAP_FMAC3 ns3__WSCluster *** SOAP_FMAC4 soap_get_PointerToPointerTons3__WSCluster(struct soap*, ns3__WSCluster ***, const char*, const char*);
SOAP_FMAC3 ns3__WSCluster *** SOAP_FMAC4 soap_in_PointerToPointerTons3__WSCluster(struct soap*, const char*, ns3__WSCluster ***, const char*);

#ifndef SOAP_TYPE_PointerTons3__WSCluster
#define SOAP_TYPE_PointerTons3__WSCluster (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__WSCluster(struct soap*, ns3__WSCluster *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__WSCluster(struct soap*, ns3__WSCluster *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__WSCluster(struct soap*, const char *, int, ns3__WSCluster *const*, const char *);
SOAP_FMAC3 ns3__WSCluster ** SOAP_FMAC4 soap_get_PointerTons3__WSCluster(struct soap*, ns3__WSCluster **, const char*, const char*);
SOAP_FMAC3 ns3__WSCluster ** SOAP_FMAC4 soap_in_PointerTons3__WSCluster(struct soap*, const char*, ns3__WSCluster **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons3__WSNode
#define SOAP_TYPE_PointerToPointerTons3__WSNode (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons3__WSNode(struct soap*, ns3__WSNode **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons3__WSNode(struct soap*, ns3__WSNode **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons3__WSNode(struct soap*, const char *, int, ns3__WSNode **const*, const char *);
SOAP_FMAC3 ns3__WSNode *** SOAP_FMAC4 soap_get_PointerToPointerTons3__WSNode(struct soap*, ns3__WSNode ***, const char*, const char*);
SOAP_FMAC3 ns3__WSNode *** SOAP_FMAC4 soap_in_PointerToPointerTons3__WSNode(struct soap*, const char*, ns3__WSNode ***, const char*);

#ifndef SOAP_TYPE_PointerTons3__WSNode
#define SOAP_TYPE_PointerTons3__WSNode (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__WSNode(struct soap*, ns3__WSNode *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__WSNode(struct soap*, ns3__WSNode *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__WSNode(struct soap*, const char *, int, ns3__WSNode *const*, const char *);
SOAP_FMAC3 ns3__WSNode ** SOAP_FMAC4 soap_get_PointerTons3__WSNode(struct soap*, ns3__WSNode **, const char*, const char*);
SOAP_FMAC3 ns3__WSNode ** SOAP_FMAC4 soap_in_PointerTons3__WSNode(struct soap*, const char*, ns3__WSNode **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons3__Result
#define SOAP_TYPE_PointerToPointerTons3__Result (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons3__Result(struct soap*, ns3__Result **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons3__Result(struct soap*, ns3__Result **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons3__Result(struct soap*, const char *, int, ns3__Result **const*, const char *);
SOAP_FMAC3 ns3__Result *** SOAP_FMAC4 soap_get_PointerToPointerTons3__Result(struct soap*, ns3__Result ***, const char*, const char*);
SOAP_FMAC3 ns3__Result *** SOAP_FMAC4 soap_in_PointerToPointerTons3__Result(struct soap*, const char*, ns3__Result ***, const char*);

#ifndef SOAP_TYPE_PointerTons3__Result
#define SOAP_TYPE_PointerTons3__Result (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__Result(struct soap*, ns3__Result *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__Result(struct soap*, ns3__Result *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__Result(struct soap*, const char *, int, ns3__Result *const*, const char *);
SOAP_FMAC3 ns3__Result ** SOAP_FMAC4 soap_get_PointerTons3__Result(struct soap*, ns3__Result **, const char*, const char*);
SOAP_FMAC3 ns3__Result ** SOAP_FMAC4 soap_in_PointerTons3__Result(struct soap*, const char*, ns3__Result **, const char*);

#ifndef SOAP_TYPE_PointerTons3__WSFarm
#define SOAP_TYPE_PointerTons3__WSFarm (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__WSFarm(struct soap*, ns3__WSFarm *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__WSFarm(struct soap*, ns3__WSFarm *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__WSFarm(struct soap*, const char *, int, ns3__WSFarm *const*, const char *);
SOAP_FMAC3 ns3__WSFarm ** SOAP_FMAC4 soap_get_PointerTons3__WSFarm(struct soap*, ns3__WSFarm **, const char*, const char*);
SOAP_FMAC3 ns3__WSFarm ** SOAP_FMAC4 soap_in_PointerTons3__WSFarm(struct soap*, const char*, ns3__WSFarm **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREWSCluster
#define SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREWSCluster (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, ArrayOf_USCOREtns1_USCOREWSCluster *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, ArrayOf_USCOREtns1_USCOREWSCluster *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, const char *, int, ArrayOf_USCOREtns1_USCOREWSCluster *const*, const char *);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSCluster ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, ArrayOf_USCOREtns1_USCOREWSCluster **, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSCluster ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCOREtns1_USCOREWSCluster(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREWSCluster **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREWSNode
#define SOAP_TYPE_PointerToArrayOf_USCOREtns1_USCOREWSNode (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCOREtns1_USCOREWSNode(struct soap*, ArrayOf_USCOREtns1_USCOREWSNode *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCOREtns1_USCOREWSNode(struct soap*, ArrayOf_USCOREtns1_USCOREWSNode *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCOREtns1_USCOREWSNode(struct soap*, const char *, int, ArrayOf_USCOREtns1_USCOREWSNode *const*, const char *);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSNode ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCOREtns1_USCOREWSNode(struct soap*, ArrayOf_USCOREtns1_USCOREWSNode **, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCOREtns1_USCOREWSNode ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCOREtns1_USCOREWSNode(struct soap*, const char*, ArrayOf_USCOREtns1_USCOREWSNode **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_PointerToArrayOf_USCORExsd_USCOREstring (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, ArrayOf_USCORExsd_USCOREstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, ArrayOf_USCORExsd_USCOREstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, const char *, int, ArrayOf_USCORExsd_USCOREstring *const*, const char *);
SOAP_FMAC3 ArrayOf_USCORExsd_USCOREstring ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, ArrayOf_USCORExsd_USCOREstring **, const char*, const char*);
SOAP_FMAC3 ArrayOf_USCORExsd_USCOREstring ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, ArrayOf_USCORExsd_USCOREstring **, const char*);

#ifndef SOAP_TYPE_PointerTons2__Map
#define SOAP_TYPE_PointerTons2__Map (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__Map(struct soap*, ns2__Map *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__Map(struct soap*, ns2__Map *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__Map(struct soap*, const char *, int, ns2__Map *const*, const char *);
SOAP_FMAC3 ns2__Map ** SOAP_FMAC4 soap_get_PointerTons2__Map(struct soap*, ns2__Map **, const char*, const char*);
SOAP_FMAC3 ns2__Map ** SOAP_FMAC4 soap_in_PointerTons2__Map(struct soap*, const char*, ns2__Map **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_PointerTons2__mapItem
#define SOAP_TYPE_PointerTons2__mapItem (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__mapItem(struct soap*, ns2__mapItem *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__mapItem(struct soap*, ns2__mapItem *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__mapItem(struct soap*, const char *, int, ns2__mapItem *const*, const char *);
SOAP_FMAC3 ns2__mapItem ** SOAP_FMAC4 soap_get_PointerTons2__mapItem(struct soap*, ns2__mapItem **, const char*, const char*);
SOAP_FMAC3 ns2__mapItem ** SOAP_FMAC4 soap_in_PointerTons2__mapItem(struct soap*, const char*, ns2__mapItem **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__anyType
#define SOAP_TYPE_PointerToxsd__anyType (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__anyType(struct soap*, xsd__anyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__anyType(struct soap*, xsd__anyType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__anyType(struct soap*, const char *, int, xsd__anyType *const*, const char *);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_get_PointerToxsd__anyType(struct soap*, xsd__anyType **, const char*, const char*);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_in_PointerToxsd__anyType(struct soap*, const char*, xsd__anyType **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__mapItem
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__mapItem (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, std::vector<ns2__mapItem * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, const std::vector<ns2__mapItem * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, const char*, int, const std::vector<ns2__mapItem * >*, const char*);
SOAP_FMAC3 std::vector<ns2__mapItem * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, const char*, std::vector<ns2__mapItem * >*, const char*);
SOAP_FMAC5 std::vector<ns2__mapItem * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, std::vector<ns2__mapItem * >*);
SOAP_FMAC3 std::vector<ns2__mapItem * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__mapItem(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
